# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flint < Formula
  desc "Flint is a frontmatter linter written in Go"
  homepage ""
  version "0.0.5"
  license "MIT"

  depends_on "go" => :optional
  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hay-kot/flint/releases/download/v0.0.5/flint_0.0.5_Darwin_arm64.zip"
      sha256 "40f4de48f708c977bf2f915f10f7c3b7f52a604b363e88051742bcc8aa828717"

      def install
        bin.install "flint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hay-kot/flint/releases/download/v0.0.5/flint_0.0.5_Darwin_x86_64.zip"
      sha256 "8f522924c9c81fa839654026f4af05c3b2454e33b56299128c39bf8526ed3d11"

      def install
        bin.install "flint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hay-kot/flint/releases/download/v0.0.5/flint_0.0.5_Linux_x86_64.zip"
      sha256 "e4451bbe148ffcbd398c1ffbdac34315185702335f10157219a730ab51c41444"

      def install
        bin.install "flint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hay-kot/flint/releases/download/v0.0.5/flint_0.0.5_Linux_arm64.zip"
      sha256 "41123ef6e49208c9452f3ee226b5b83ffef75485d3f3ae2b94e3d93dd63ddf7d"

      def install
        bin.install "flint"
      end
    end
  end

  test do
    system "#{bin}/flint -version"
  end
end
