# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flint < Formula
  desc "Flint is a frontmatter linter written in Go"
  homepage ""
  version "0.0.3"
  license "MIT"

  depends_on "go" => :optional
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hay-kot/flint/releases/download/v0.0.3/flint_0.0.3_Darwin_x86_64.zip"
      sha256 "358c80b49c222fd7b98c1bb4969383e8d57fbc329831dd589959e5439e66541a"

      def install
        bin.install "flint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hay-kot/flint/releases/download/v0.0.3/flint_0.0.3_Darwin_arm64.zip"
      sha256 "832c7c590d636c37bb0d0e97fcfc43329342ab2c43dca1d7ec222868e94f78ba"

      def install
        bin.install "flint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hay-kot/flint/releases/download/v0.0.3/flint_0.0.3_Linux_arm64.zip"
      sha256 "b4e6cdc4dbbc1c9e67116391afd6c29a034cadca1f4ecb8c3467947a914dc551"

      def install
        bin.install "flint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hay-kot/flint/releases/download/v0.0.3/flint_0.0.3_Linux_x86_64.zip"
      sha256 "7b9f45eeab9d21b68f78ac119b43626efcefad1dccd4e73fb218f4c8ff1169ce"

      def install
        bin.install "flint"
      end
    end
  end

  test do
    system "#{bin}/flint -version"
  end
end
